### ISSUE TITLE
Compatible for M2.3.4?

### ISSUE THREAD

**Issue by Esteraa** [tig-nl/gls-magento2#1]
The module is not compatible for Magento version 2.3.4. When will you update the module?
![image](https://user-images.githubusercontent.com/30499229/74839169-1b970980-5325-11ea-864a-d799a3dd55d8.png)

**Comment by tig-daanvandenbergh** [comment]
Hi @Esteraa,

We've tested the extension with the latest Magento-versions and it works. In the next release we'll modify the version numbers in the support-tab.
