### ISSUE TITLE
[QUESTION] Compatible for M2.4

### ISSUE THREAD

**Issue by erwinromkes** [tig-nl/gls-magento2#10]
**Question**
Magento 2.4 is out for some time, is there an 2.4 compatible update in the works?

**Comment by tig-jaspersmits** [comment]
Hi @erwinromkes ,

Thanks for your message. The extension was tested with Magento 2.4.1 and we didn't run into any problems. So you should be able to install this for 2.4.0 as well.

Kind regards,
Jasper
TIG

**Comment by erwinromkes** [comment]
Great, in that case: https://github.com/tig-nl/gls-magento2/pull/11 :+1:

**Comment by tig-jaspersmits** [comment]
Hi @erwinromkes , thanks. Fair point.. I'll inform our team to push those changes.

Kind regards,
Jasper
TIG

**Comment by tig-daanvandenbergh** [comment]
Thanks, @erwinromkes. v1.3.2 offers compatibility (and more importantly installability ;)) for Magento 2.4.x
