### ISSUE TITLE
[FEATURE] Disable shipping day options

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#12]
**Please rephrase the following line:**

As a Magento 2 owner I'd like to offer my clients only to click GLS Bezorging without choosing the day of the delivery when there is only one item to choose from. I would no like to display the option at all. 

![Schermafbeelding 2020-12-11 om 15 00 50](https://user-images.githubusercontent.com/639822/101912385-f4fed380-3bc1-11eb-9bd5-caa37bf4114c.png)

The mail confirmation of the order makes it even more confuse. It can be read as the day that the order will be shipped instead of delivered. 

![Schermafbeelding 2020-12-11 om 15 03 14](https://user-images.githubusercontent.com/639822/101912534-2d061680-3bc2-11eb-8f1e-be4bc2502f32.png)

**Suggestions and background**

- [ ] add an option to remove the estimated delivery date from the mail order confirmation
- [ ] When _FlexDeliveryService_  is set to _Disable_ I am not expecting to see the single option to select the date of delivery

**Comment by tig-jaspersmits** [comment]
Hi @hans2103 ,

Thanks for this feature request. I'll add it to our backlog.

Kind regards,
Jasper

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst his this issue been fixed? Not seeing a commit or reference

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103,

This should also be fixed, you should be able to disable the options.

Have a great day,
Jeffrey
