### ISSUE TITLE
[FEATURE] change parcel count

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#13]
**Please rephrase the following line:**

As a shop owner I'd like to be able to change the parcel count in order to ship heavy orders with multiple parcels

**Suggestions and background**

We are using both TIG/PostNL as TIG/GLS
Using PostNL it is possible to change the parcel count while creating a shipment. 
We would like to be able to do the same for GLS shipments

![Schermafbeelding 2020-12-21 om 09 50 01](https://user-images.githubusercontent.com/639822/102757645-ece92580-4371-11eb-8f62-d52af0a567cd.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

Thank you for thinking along with us! I will discuss this with the team.

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst 
Can you inform me the result of the mentioned discussion? Will the feature be added to the Module?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @hans2103 ,

We have placed it on the backlog, but we cannot give you an ETA because we don't have one yet. 

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst can you toss a ball at GLS and request resources to start working on this request?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

Just checked out the latest version and looks like this has been added. Can you update your GLS extension on a staging environment? 
![image](https://user-images.githubusercontent.com/23314965/137919194-ef9e26f2-71cb-46ef-af3f-23c5b93bbf01.png)

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst I am using both tig/gls-magento and tig/postnl-magento 
Looking at the Sales section I only see PostNL. I am not seeing GLS
<img width="571" alt="Schermafbeelding 2021-10-20 om 11 15 23" src="https://user-images.githubusercontent.com/639822/138065034-d97d67f6-4c62-41b5-b1a0-b2824d82228d.png">

**Comment by tig-jeffreybranderhorst** [comment]
Hey @hans2103 ,

This seems to be a bug with if you use both extensions. I will place this on our backlog.  I have also tested this on my test site.

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst has this bug been solved yet? Should the label of this issue be changed from enhancement to bug?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @hans2103,

It has not been solved yet, the issue is still placed on our backlog! I will change the label of the issue, thank you! 

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
:wastebasket: house cleaning my issues. Closing this one because it will never be implemented
