### ISSUE TITLE
[QUESTION] Does it work with GLS Italy?

### ISSUE THREAD

**Issue by tanolalano** [tig-nl/gls-magento2#14]
**Question**
I'd like to know if this module can work with GLS- ITaly.
Thanks

**Comment by tig-daanvandenbergh** [comment]
Hi @tanolalano,

Thank you for your interest in our module! 😃 

Unfortunately, no. This module works exclusively with GLS Netherlands' API.

**Comment by tanolalano** [comment]
Thanks you for your quick response
