### ISSUE TITLE
[QUESTION] Change flat price on store view

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#15]
**Question**
Ask your question in an arbitrary form without insulting someone. Please make sure it's worded well enough to be understood and remove this line.

Using GLS I want to be able to change the price for flat rate on scope = Store view. 
How can this be achieved?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

You can change the shipping cost on default and store scope. On store view scope there is no option to change shipping cost in magento.

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
The Store Scope cannot be selected from the dropdown to change scopes.
Therefor the price field is only visible on default.
How to change the price on scope store?


Is it possible to add this on the list of feature requests?
- allow shopping cost to be configured on scope store view

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

You are right, was not using the right names in my last message. I will put this on the backlog and we will talk about this with GLS! 
Thank you for submitting this and helping us improve the extension.

Have a great day,
Jeffrey

**Comment by hans2103** [comment]
@tig-jeffreybranderhorst his this issue been fixed? Not seeing a commit or reference

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103,

Yes! This should have been fixed in the newest version of the extension.

Have a great day,
Jeffrey
