### ISSUE TITLE
[FEATURE] disable GLS bezorgdag

### ISSUE THREAD

**Issue by basdeve** [tig-nl/gls-magento2#16]
As a webshop owner I'd like to disable expected delivery date so customers don't get a false expectation for backorder products

It would be great if there would be an option in the backend whether to show GLS bezorgdag or not. Ideally, you would only want to show GLS bezorgdag for 'in stock' products, and only disable GLS bezorgdag for backorder products.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @basdeve 

Thank you for submitting this enhancement! We will put it on the backlog, thank you for helping making the extension even better!

Have a great day,
Jeffrey
