### ISSUE TITLE
Gls Delivery Option is never saved to Order.

### ISSUE THREAD

**Issue by clemheld** [tig-nl/gls-magento2#17]
https://github.com/tig-nl/gls-magento2/blob/93101dacdf673365927ddb58ca8266412b580d3d/Plugin/Quote/Model/QuoteManagement.php#L147

The GLS Delivery Option data is never saved to the order, because AfterPlaceOrder will execute without having any data in said object, because that data is only saved later on in the same function. 

What happens is, that object returns null and the function returns the order id.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @clemheld ,

We will put this on our backlog and discuss this with GLS they need to decide when this is being pickup.  Thank you for submitting this and helping us to make the extension even better!

Have great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @clemheld ,

Could you contact us at support@tig.nl then we can talk more about this problem!
It is still on our backlog so that has not changed!

Have a nice day,
Jeffrey
