### ISSUE TITLE
[BUG] Something (?) went wrong while importing GLS rates

### ISSUE THREAD

**Issue by vandijkstef** [tig-nl/gls-magento2#18]
**To Reproduce**
1. Go to Configuration -> Sales -> Shipping Methods
2. Switch to 'website configuration scope'
3. Click on Export CSV
4. Upload that same CSV on the 'import rates'
5. Click save
6. "Something" went wrong

**Expected result**
A clean import of GLS rates. Other then that, a more clear error message. At first I was thinking I broke the CSV, but since it also breaks on the data it exports itself I guess something else is up.

**Actual result**
Shows error `Something went wrong while importing GLS rates.`. No database changes are made as far as I can see.

**Workaround**
Manually hack this into the database, with the risk of many unintended side-effects

**Screenshots**
Nope

** Please complete the following information**
- Magento version: "magento/product-community-edition": "2.3.4",
- PHP version: 7.3.23
- TIG GLS version: 1.3.2

**Comment by tig-jeffreybranderhorst** [comment]
Hi @vandijkstef ,

Could you contact us at support@tig.nl with your rates so we can investigate this further?

Have a great day,
Jeffrey

**Comment by jghaanstra** [comment]
I have the same issue with a very simple import csv file. Should I contact support trough email as well?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jghaanstra 

You can contact us for sure, so we van help you further. If I read this I feel like this is a setting for the shipping method. Contact us at support@tig.nl and we will be able to assist you further.

Have a great day,
Jeffrey

**Comment by vandijkstef** [comment]
Hi @tig-jeffreybranderhorst ,

Did you receive my email/CSV? Haven't heard back from you guys yet.

Thanks!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @vandijkstef ,

We don't see any open issues. Did you receive an issue number for our system? 
If you have an issue number please tell me this one so I can check the status. 

Have a great day,
Jeffrey

**Comment by vandijkstef** [comment]
Hi @tig-jeffreybranderhorst ,

No I did not receive an issue number from your system. I've send the email within minutes after you requested to. Also I've never received a 'bounce' or 'undelivered'.

I just send it again, this time without attachment but the raw CSV data pasted under the email. But you can also use the 'default' CSV you can download from the Magento Admin since its based on that.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @vandijkstef,

Looks like we are not receiving your emails, could you give us your mail so I can contact you?

Have a great day,
Jeffrey

**Comment by vandijkstef** [comment]
@tig-jeffreybranderhorst Uh oh! That is very interesting... You can reach me on stef@vandijkstef.nl

**Comment by tig-jeffreybranderhorst** [comment]
Hey @vandijkstef,

I'm going to contact you! Thank you!

Have a great day,
Jeffrey
