### ISSUE TITLE
Improvement: Add tablerate for weight

### ISSUE THREAD

**Issue by Esteraa** [tig-nl/gls-magento2#2]
Improve tablerate condition. The GLS module uses prics vs. destionation for tablerates. We would like to use weight vs. destination as input for tablerates. 

Maybe it could be the same as the Magento tablerate conditions:

![image](https://user-images.githubusercontent.com/30499229/76405571-9f726d80-6388-11ea-94d4-f2d4eaefa96e.png)

Please let me know what your plans are on this topic, as for now we can't use it for our customer.

**Comment by tig-jeffreybranderhorst** [comment]
Hi Esteraa,

Thank you for your submission, I'm going to put this on the backlog and consult this with GLS.
Thank you for helping with improving the extension if you got more feature wishes we would like to hear them!

Kind regards,
Jeffrey
