### ISSUE TITLE
[FEATURE] add config fields sender address

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#22]
**Please rephrase the following line:**

As a website owner I'd like to be able to change the sender address in order to be able to act as a dropshipping.

**Suggestions and background**

Magento admin > Store > Settings > Configuration > Sales > PostNL  > Basic > Sender Address

This block is missing in the GLS module. Please add it to the GLS module too

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103 ,

Thank you for submitting this feature, I will be added this to the backlog. 

Have a great day,
Jeffrey

**Comment by SolsWebdesign** [comment]
Hi @hans2103, @tig-jeffreybranderhorst I have added the code in a pull request  #25

**Comment by hans2103** [comment]
:wastebasket: house cleaning my issues. Closing this one because it will never be implemented
