### ISSUE TITLE
[FEATURE] Disable specific weekdays for delivery

### ISSUE THREAD

**Issue by paul-stolk-webdiensten** [tig-nl/gls-magento2#27]
**Please rephrase the following line:**

As a webshop owner I'd like to disable certain weekdays for delivery in order to prevent showing delivery dates I cannot deliver. 

For example: on Sundays I do not ship any orders, meaning when someone orders on Sunday I cannot deliver on Monday. Currently, Monday is available as delivery day.
Ideally I would like to be able to select which weekdays I can delivery in the admin panel.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @paul-stolk-webdiensten,

Thank you for this feature request! I will add it to our backlog. This means we will talk about this request with GLS and see if and when we can add this feature! 

Have a great day,
Jeffrey

**Comment by paul-stolk-webdiensten** [comment]
Hi Jeffrey,

Thank you for your reply. In my opinion this is a basic feature of the module. Do you have any idea in what timeframe this can be realized? Otherwise we will have to look into custom changes for this module.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @paul-stolk-webdiensten,

I cannot give a timeframe yet, the reason for this is we first need to talk about this feature with GLS. 

Have a great day,
Jeffrey

**Comment by irisvandenhout** [comment]
Hi @tig-jeffreybranderhorst 

Do you have a timeframe for this feature yet? Or is there a different way to fix this issue?

Have a great day,
Iris

**Comment by tig-jeffreybranderhorst** [comment]
Hi @irisvandenhout ,

Thanks for getting in touch. The WooCommerce plugin/Magento 2 extension by
GLS, built by TIG, will expire in its current form. TIG will no longer provide
support from 31 May 2022 onwards. The current extension will be available until
the end of the year.
Should you have any questions about this, please contact the IT support
department of GLS at [helpdesk@gls.nl](mailto:helpdesk@gls.nl). GLS has alternative plugins available.

Have a great day,
Jeffrey
