### ISSUE TITLE
Access denied due to missing subscription key

### ISSUE THREAD

**Issue by jacktran2703** [tig-nl/gls-magento2#3]
Hello Team,

I'm getting an error message "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API".
I know subscription key is required but I don't know where I can find subscription key.
I contacted GLS support but they even don't know about "Subscription key": Ocp-Apim-Subscription-Key.
Can you please advise?

Thank you so much!

**Comment by niclashoyer** [comment]
@jacktran2703 we've got the same problem. Searching for this header just leads to Windows Azure platform: https://stackoverflow.com/questions/40867834/where-to-find-my-ocp-apim-subscription-key-in-windows-azure

I don't know how this fits together... Did you find a solution?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jacktran2703 and @niclashoyer,

Thank you for contacting us. We will investigate it and come back to you with an answer.

Have a great day,
Jeffrey

**Comment by jacktran2703** [comment]
> @jacktran2703 we've got the same problem. Searching for this header just leads to Windows Azure platform: https://stackoverflow.com/questions/40867834/where-to-find-my-ocp-apim-subscription-key-in-windows-azure
> 
> I don't know how this fits together... Did you find a solution?

Hi @niclashoyer ,
I have not found a solution yet. I'm waiting for the feedback from support.

**Comment by jacktran2703** [comment]
> Hi @jacktran2703 and @niclashoyer,
> 
> Thank you for contacting us. We will investigate it and come back to you with an answer.
> 
> Have a great day,
> Jeffrey

Hi @tig-jeffreybranderhorst ,

Thanks for your reply.
I'm looking forward to your answer soon.
Have a nice day!

Best Regards,
Jack

**Comment by tig-jeffreybranderhorst** [comment]
Hey @jacktran2703 and @niclashoyer,

You can test the extension with the following credentials. 
user: apitest3@gls-netherlands,com
password: TestUser
apikey: 8c78181337114438be1c6bb95a755ccf

Thank you for submitting this issue we will make sure that following versions this is already filled in. 

Have a great day,
Jeffrey

**Comment by jacktran2703** [comment]
Hey @tig-jeffreybranderhorst,

Thanks for your help.
I have correct credentials now but username should be:
**apitest3@gls-netherlands.com** instead of **apitest3@gls-netherlands,com**.
Thanks again for your help. Have a nice day!

Best Regards,
Jack

**Comment by niclashoyer** [comment]
@tig-jeffreybranderhorst 

Thank you for the credentials. As these are credentials for gls-netherlands does the extension just work for GLS NL? Do we need to contact GLS directly to get API credentials? I can't see anything like this in the GLS merchant login.

**Comment by tig-daanvandenbergh** [comment]
HI @niclashoyer,

Yes. This extension integrates the delivery services of GLS Netherlands into Magento 2.

In the Magento Marketplace this is made clear in the documentation.  I see now that it's not clear in the Readme in Github. I will adjust that.

**Comment by michalzimniak** [comment]
Hi, @tig-daanvandenbergh, to make it clear - this plugin will work only for GLS Netherlands and there is no possibile to integrate it to other GLS services like GLS Germany etc?

**Comment by tig-daanvandenbergh** [comment]
Hi @michalzimniak,

Sorry. I missed your message, because I didn't receive a notification.

In short, no, it's not possible to integrate it with GLS departments in other countries. GLS Netherlands maintains its own API, so this extension is built specifically to work with their API.
