### ISSUE TITLE
please create new tag based on this version in composer

### ISSUE THREAD

**Issue by hans2103** [tig-nl/gls-magento2#31]
according to your releases on https://github.com/tig-nl/gls-magento2/releases the most recent version is 1.3.2
according to composer.json in the master branch of your repo the most recent version is 1.4.0 https://github.com/tig-nl/gls-magento2/blob/3cc04be6a28cced8f4b601b886e8e9907234619c/composer.json#L11

please create a new tag 1.4.0 (or even better... merge fixes into 1.4.1)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @hans2103,

The release notes and tag were set on private. Just changed it to live! Thank you for the message! 

Have a great day,
Jeffrey
