### ISSUE TITLE
[BUG] Mage 2.4.4 product/order grid filter/search

### ISSUE THREAD

**Issue by vandijkstef** [tig-nl/gls-magento2#36]
I've got an issue after upgrading to Mage2.4.4. Been able to track it down to this module. Issue is reported here: https://github.com/magento/magento2/issues/35781

I will put work into this, just raising this issue to notify anyone this module doesn't seem compatible with Mage2.4.4 for this specific reason. 

Tested on PHP 7.4 and 8.1 and with a clean version of 1.4.0 of TIG_GLS.

**Comment by tig-jeffreybranderhorst** [comment]
Dear @vandijkstef ,

Thanks for getting in touch. The Magento 2 extension by GLS, built by TIG, will expire in its current form. TIG will no longer provide support from 31 May 2022 onwards. The current extension will be available until the end of the year.

Should you have any questions about this, please contact the IT support
department of GLS at [helpdesk@gls.nl](mailto:helpdesk@gls.nl). GLS has alternative plugins available.
Kind regards,
Jeffrey

**Comment by vandijkstef** [comment]
> Should you have any questions about this...

We had, lots of them... Sadly we're missing out on features we have to wait on for a month or two.

Not a complete fix, but it seems workable for our use cases. I deleted 3 files from the module:

- /TIG/GLS/view/adminhtml/ui_component/sales_order_grid.xml
- /TIG/GLS/view/base/requirejs-config.js
- /TIG/GLS/view/base/ui_component/etc/definition.xml

**Comment by tig-jeffreybranderhorst** [comment]
Hi @vandijkstef ,

You can still contact GLS for adding/changing the module. They give the support themselves now and also the development. 

Have a great day,
Jeffrey
