### ISSUE TITLE
/etc/acl.xml has been removed

### ISSUE THREAD

**Issue by plus8digital** [tig-nl/gls-magento2#37]
**To Reproduce**

**Expected result**

**Actual result**
Describe the actual result

**Workaround**
Describe the temporarily workaround or if none exists write "None"

**Screenshots**

** Please complete the following information**
- Magento version: Magento 2.3.4
- PHP version: 7.4
- TIG GLS version: 1.3.1

------------------------------------------------
 /etc/acl.xml file, added in a previous pull request has been removed

Therefore if a user has a custom role, then they can not see the configuration section as it is not possible to allow it in the role configuration.

Workaround..
Have added /etc/acl.xml

**Comment by tig-jeffreybranderhorst** [comment]
Hi @plus8digital ,

Thanks for getting in touch. The Magento 2 extension by GLS, built by TIG, will expire in its current form. TIG will no longer provide support from 31 May 2022 onwards. The current extension will be available until the end of the year.

Should you have any questions about this, please contact the IT support
department of GLS at [helpdesk@gls.nl](mailto:helpdesk@gls.nl). GLS has alternative plugins available.
Kind regards,
Jeffrey
